#!/usr/bin/env python3
"""Tests for the v3.3 companion and update-check scripts.

Deterministic and offline: the update checker is exercised through its
opt-out switch and its cache, never the network.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import textwrap
import time
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"
PY = sys.executable


def run(args, cwd, env=None):
    e = dict(os.environ)
    e.update(env or {})
    p = subprocess.run([PY, *args], cwd=cwd, capture_output=True, text=True, env=e)
    return p.returncode, p.stdout, p.stderr


class TestDetectCompanions(unittest.TestCase):
    def test_writes_json_and_exits_zero_when_nothing_installed(self):
        d = Path(tempfile.mkdtemp())
        try:
            # Empty PATH hides any `graphify` CLI on the machine; the Python
            # module check uses the test interpreter and is reported, not asserted.
            code, out, err = run([SCRIPTS / "detect_companions.py"], d,
                                 {"HOME": str(d), "PATH": str(d)})
            self.assertEqual(code, 0, err)
            data = json.loads((d / ".harness/companions.json").read_text())
            for k in ("uupm", "ponytail", "rtk"):
                self.assertFalse(data[k]["installed"], k)
            self.assertIsNone(data["graphify"]["cli"])
            self.assertIsInstance(data["graphify"]["installed"], bool)
            self.assertEqual(data["warnings"], [])
        finally:
            shutil.rmtree(d)

    def test_unscoped_ponytail_raises_a_warning(self):
        d = Path(tempfile.mkdtemp())
        try:
            (d / ".claude/plugins/x/ponytail/hooks").mkdir(parents=True)
            (d / ".claude/plugins/x/ponytail/hooks/ponytail-subagent.js").write_text("")
            code, out, err = run([SCRIPTS / "detect_companions.py"], d, {"HOME": str(d)})
            self.assertEqual(code, 0)
            data = json.loads((d / ".harness/companions.json").read_text())
            self.assertTrue(data["ponytail"]["installed"])
            self.assertFalse(data["ponytail"]["scoped_to_generator"])
            self.assertTrue(any("PONYTAIL_SUBAGENT_MATCHER" in w for w in data["warnings"]))
            code, out, err = run([SCRIPTS / "detect_companions.py"], d,
                                 {"HOME": str(d), "PONYTAIL_SUBAGENT_MATCHER": "^generator$"})
            data = json.loads((d / ".harness/companions.json").read_text())
            self.assertTrue(data["ponytail"]["scoped_to_generator"])
            self.assertEqual(data["warnings"], [])
        finally:
            shutil.rmtree(d)


class TestUupmDesignSystem(unittest.TestCase):
    def test_exit_2_without_companions_or_uupm(self):
        d = Path(tempfile.mkdtemp())
        try:
            code, out, err = run([SCRIPTS / "uupm_design_system.py", "--query", "x", "--project", "y"], d)
            self.assertEqual(code, 2)
            (d / ".harness").mkdir()
            (d / ".harness/companions.json").write_text(json.dumps({"uupm": {"installed": False}}))
            code, out, err = run([SCRIPTS / "uupm_design_system.py", "--query", "x", "--project", "y"], d)
            self.assertEqual(code, 2)
            self.assertIn("by hand", err)
        finally:
            shutil.rmtree(d)

    def test_draft_from_a_fake_search_py(self):
        d = Path(tempfile.mkdtemp())
        try:
            fake = d / "search.py"
            fake.write_text(textwrap.dedent("""
                import sys
                print("## Design System")
                print("### Colors\\n- primary: #112233")
                """))
            (d / ".harness").mkdir()
            (d / ".harness/companions.json").write_text(json.dumps(
                {"uupm": {"installed": True, "search_py": str(fake), "version": "9.9.9"}}))
            code, out, err = run([SCRIPTS / "uupm_design_system.py", "--query", "saas", "--project", "P"], d)
            self.assertEqual(code, 0, err)
            doc = (d / "docs/03b-design-system.md").read_text()
            self.assertIn("DRAFT generated by UI UX Pro Max", doc)
            self.assertIn("- primary: #112233", doc)
            self.assertNotIn("## Design System\n### Colors", doc)  # tool title dropped
            self.assertIn("search.py 9.9.9", doc)
            code, out, err = run([SCRIPTS / "uupm_design_system.py", "--query", "saas", "--project", "P"], d)
            self.assertEqual(code, 0)
            self.assertIn("--force", err)  # existing draft is not overwritten
        finally:
            shutil.rmtree(d)


class TestCheckUpdates(unittest.TestCase):
    def test_opt_out_env_prints_nothing_and_exits_zero(self):
        d = Path(tempfile.mkdtemp())
        try:
            code, out, err = run([SCRIPTS / "check_updates.py", "--hook"], d,
                                 {"HOME": str(d), "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1"})
            self.assertEqual(code, 0)
            self.assertEqual(out, "")
        finally:
            shutil.rmtree(d)

    def test_fresh_cache_is_used_without_network(self):
        d = Path(tempfile.mkdtemp())
        try:
            cache = d / ".claude/asdr-update-check.json"
            cache.parent.mkdir(parents=True)
            cache.write_text(json.dumps({
                "checked_at": int(time.time()),
                "updates": [{"name": "ai-software-delivery-room", "installed": "3.0.0",
                             "latest": "3.3.0", "optional": False, "benefits": "x",
                             "update_command": "claude plugin update ai-software-delivery-room@asdr"}],
                "up_to_date": [], "skipped": []}))
            code, out, err = run([SCRIPTS / "check_updates.py", "--hook"], d, {"HOME": str(d)})
            self.assertEqual(code, 0, err)
            self.assertIn("3.0.0→3.3.0", out)
            code, out, err = run([SCRIPTS / "check_updates.py", "--json"], d, {"HOME": str(d)})
            self.assertEqual(json.loads(out)["updates"][0]["latest"], "3.3.0")
        finally:
            shutil.rmtree(d)

    def test_upstream_json_is_consistent_with_marketplace(self):
        up = json.loads((SCRIPTS / "upstream.json").read_text()); up.pop("_comment", None)
        mp = json.loads((REPO / ".claude-plugin/marketplace.json").read_text())
        names = {p["name"] for p in mp["plugins"]}
        for n, spec in up.items():
            if spec["kind"] == "claude-plugin":
                self.assertIn(n, names, f"{n} in upstream.json but not in marketplace.json")
                self.assertTrue(spec["manifest_url"].endswith("/.claude-plugin/plugin.json"))
        asdr = next(p for p in mp["plugins"] if p["name"] == "ai-software-delivery-room")
        self.assertNotIn("version", asdr, "ASDR marketplace entry must not carry a version")
        self.assertIn("ui-ux-pro-max", asdr.get("dependencies", []))


if __name__ == "__main__":
    unittest.main()
