#!/usr/bin/env python3
"""Draft docs/03b-design-system.md with UI UX Pro Max, if installed.

Usage:
  python3 uupm_design_system.py --query "<product_type> <industry> <keywords>" \
      --project "<Project Name>" [--out docs/03b-design-system.md] \
      [--companions .harness/companions.json]

Exit codes:
  0  draft written — executor MUST still review fit and fill §1, §7, §10
  2  UI UX Pro Max not installed — executor writes the doc by hand from
     .harness/templates/design-system.md
  1  search.py ran but failed — treat as exit 2 and record the error

The generator is keyword matching over a static dataset, not reasoning
about the product. It reliably produces coherent tokens (colors with
contrast pairs, font pairings, a checklist); it does NOT reliably pick the
right layout pattern for the product type. That is why the draft lands
under a provenance header and stage-qa grades fit against docs/01.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

HEADER = """# Design System

<!-- Save as: docs/03b-design-system.md · Written by: solution-architect
DRAFT generated by UI UX Pro Max (keyword-matched, not reasoned).
Executor: fill §1, §7 and §10 from the template
(.harness/templates/design-system.md), review §2/§3 against
docs/01-product-brief.md, and delete this notice when done. -->

## 1. Product context (from docs/01, docs/02)

<Fill from the brief: product type, industry, audience/device, brand
constraints, constraining requirement IDs.>

"""

FOOTER = """

## 7. Component inventory

<One row per component the use cases need (cite UC ids) — see template.>

## 10. Provenance and fit review

- Drafted by: UI UX Pro Max search.py {version} (`--design-system`)
- Query used: `{query}`
- Executor's fit review: <does the pattern/style match §1? what was changed
  from the draft and why — quote the brief line that drove each change>
- Open questions for the user: <…>
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--query", required=True)
    ap.add_argument("--project", required=True)
    ap.add_argument("--out", default="docs/03b-design-system.md")
    ap.add_argument("--companions", default=".harness/companions.json")
    ap.add_argument("--force", action="store_true", help="overwrite an existing draft")
    args = ap.parse_args()

    comp_path = Path(args.companions)
    if not comp_path.exists():
        print("ERROR: run detect_companions.py first", file=sys.stderr)
        return 2
    uupm = json.loads(comp_path.read_text()).get("uupm", {})
    if not uupm.get("installed"):
        print("UI UX Pro Max not installed — write docs/03b by hand from the template.",
              file=sys.stderr)
        return 2

    out = Path(args.out)
    if out.exists() and not args.force:
        print(f"{out} exists; pass --force to overwrite the draft.", file=sys.stderr)
        return 0

    cmd = [sys.executable, uupm["search_py"], args.query,
           "--design-system", "-p", args.project, "-f", "markdown"]
    try:
        run = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except subprocess.TimeoutExpired:
        print("ERROR: search.py timed out (120s)", file=sys.stderr)
        return 1
    if run.returncode != 0 or not run.stdout.strip():
        print(f"ERROR: search.py exit {run.returncode}: {run.stderr[:500]}", file=sys.stderr)
        return 1

    body = run.stdout
    # Drop the tool's own H2 title so the ASDR header is the single title.
    lines = body.splitlines()
    if lines and lines[0].startswith("## Design System"):
        lines = lines[1:]
    body = "\n".join(lines).strip()

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEADER + body + FOOTER.format(
        version=uupm.get("version") or "unknown", query=args.query))
    print(f"draft written: {out} ({len(body)} chars) — review fit before stage-qa")
    return 0


if __name__ == "__main__":
    sys.exit(main())
